name: river-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - cython
  - scikit-learn
  - pandas
  - matplotlib
  - ipympl
  - nodejs
  - bokeh
  - holoviews
  - panel
  - streamz
  - pip:
    - git+https://github.com/online-ml/river.git
